

#raw files
data_raw:
    sample: "../data/raw/sample_submission.csv"
    train: "../data/raw/train.csv"
    test: "../data/raw/test.csv"

data_clean:
    train: "../data/clean/train.csv"
    test: "../data/clean/test.csv"

